spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/m?characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:test-db;MODE=MYSQL
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:mysql-schema.sql
      data-locations: classpath:mysql-data.sql
#      schema-locations: classpath:h2-schema.sql
#      data-locations: classpath:h2-data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#sqlbard:
#  enabled: true
#  showExecuteTime: true
#  allowPathList:
#  notAllowPathList:
#  maxExecuteMillisecond: -1
#  booleanStrategy: toNumber
#  enumStrategy: toName