spring:
  datasource:
    url: jdbc:h2:mem:test-db;MODE=MYSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml

sqlbard:
  enabled: true
#  allowPathList:
#  notAllowPathList:
  showExecuteTime: true
#  maxExecuteMillisecond: -1